### ISSUE TITLE
User Story: Sort Posts By Popularity

### ISSUE THREAD

**Issue by ay0503** [CMU-313/nodebb-f24-team-tbd-1#7]
As a user, I want to be able to sort the posts by popularity so that I can see the most popular posts first.

**Comment by ErkeXia** [comment]
![cf090edbc6a0b33820d9e5c3f2998c5](https://github.com/user-attachments/assets/a970cba3-fa24-4e84-bccd-7b5572806fca)
I used the old instructions to get front-end changes to work locally by modifying node_modules, but didn’t have the time to follow the new instructions. Users can choose to sort posts by popularity.
